apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-apimeli
spec:
  selector:
    matchLabels:
      app: apimeli
  replicas: 2
  template:
    metadata:
      labels:
        app: apimeli
    spec: 
      containers:
      - name: apimeli
        image: andresmoraamado/repo-api-meli:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi