apiVersion: v1
items:
- apiVersion: autoscaling/v2
  kind: HorizontalPodAutoscaler
  metadata:
    creationTimestamp: "2022-06-15T03:09:16Z"
    name: hpa-apimeli
    namespace: apimeli
    resourceVersion: "91443"
    uid: e9d32b6f-354a-4f3b-9616-e9997f5da851
  spec:
    minReplicas: 1
    maxReplicas: 10
    metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 50
          type: Utilization
      type: Resource
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: dep-apimeli