apiVersion: v1
kind: Service
metadata:
  name: serv-apimeli
spec:
  type:  LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http
  selector:
    app: apimeli